### ISSUE TITLE
Add ability to remove dismiss animations

### ISSUE THREAD

**Issue by sgruby** [candostdagdeviren/CDAlertView#13]
I'd like the ability to remove the animations when dismissing the alert via a button. Right now, you always dismiss with the animations turned on.

**Comment by candostdagdeviren** [comment]
I'd like to do more about animations in general. As a starting point, we can include this to next release. If you want to collaborate, I'd be glad :)

**Comment by sgruby** [comment]
I don't have a huge interest in adding animations, so I'm not sure I'd be a huge help. Removing the animation should be pretty straightforward with a flag that says something like animate.

Thanks for making this alert view! It was the cleanest one I could find that let me change the font size.

**Comment by candostdagdeviren** [comment]
Thanks for using it! 
And yeah, removing the animation is an easy one. I'll try to do that as soon as possible. But don't have that much time at these times.

**Comment by candostdagdeviren** [comment]
Hi again! I've just added the hiding animation support via `hideAnimations` property. You can also set the animation duration via `hideAnimationDuration` property. If you set this property before calling `show()` method, your animations will run before removing the AlertView from view hierarchy. I'm now closing this issue. If you find any bugs or some other issues, please let me know. Happy coding!
