### ISSUE TITLE
Add ability to change spacing above and below message text

### ISSUE THREAD

**Issue by sgruby** [candostdagdeviren/CDAlertView#15]
I'd like to see an easy way to add spacing above and below the message text without having to add \n to my message string (that's a bit too much).

Thanks!

**Comment by candostdagdeviren** [comment]
I'm not sure we should implement this or not. Do you have strong arguments about this? I mean it's another customization but I don't see a general use case for that except specific reasons.

**Comment by sgruby** [comment]
I don't have a strong opinion about this. A client of mine wanted the alerts to be spaced a bit more and I was able to get away with using linefeeds in them, but I thought it was spaced a bit too much.

**Comment by candostdagdeviren** [comment]
I've added the custom view for below the message text. So we can say that part of this request is implemented. Regarding the space above message text, I think I can open spacing value to public for stackView that I used to add title and message.

**Comment by ghost** [comment]
Great, thanks!

**Comment by candostdagdeviren** [comment]
Since there is no one else requested and I'm not a fan of implementing the space below the text, closing the issue. Thanks for the idea :)
