### ISSUE TITLE
more than one textField

### ISSUE THREAD

**Issue by ghost** [candostdagdeviren/CDAlertView#17]
Can i add more than one text field to the alert view. Will you support actionSheets in the future

**Comment by candostdagdeviren** [comment]
I don't think I'll support actionsSheets in the future. For the more than one textField, I'll add a customizable view area. Then, you will be able to do whatever you want on that area :)

**Comment by KarmaDordje** [comment]
can you explain how to do this, cause I'm new in Swift. So i didn't find in code this customizable view area. Thank you.

**Comment by candostdagdeviren** [comment]
As you can see @KarmaDordje this issue is open and marked with "feature request", it is not available yet.

**Comment by KarmaDordje** [comment]
oh, sorry, okay thank you =)

**Comment by candostdagdeviren** [comment]
I added `customView` area with new release `0.6.0`. You can set customView to add two textFields. I'm closing this issue. If any issue comes up, please open another one :)
