### ISSUE TITLE
Layout issue because of LayoutConstraintsExtension

### ISSUE THREAD

**Issue by gaetano78** [candostdagdeviren/CDAlertView#23]
LayoutConstraintsExtension causes Layout issues when you use your library with some other libraries. I found this problem with CLImageEditor. The reason in the specific case, is that CLImageEditor uses, in its own extension, the same function names: setHeight, setWidth. To solve the problem, I changed the name of these functions in setHeightCD, setWidthCD. Please could you change the names of all the functions in the LayoutConstraintsExtension with some suffix such as CD?

**Comment by candostdagdeviren** [comment]
Fixed with [CDAlertView version 0.6.1](https://github.com/candostdagdeviren/CDAlertView/releases/tag/0.6.1)
