### ISSUE TITLE
No icon bug

### ISSUE THREAD

**Issue by kuraydev** [candostdagdeviren/CDAlertView#24]
Hello,
I really like your library and using it :) 
When I use it as .notification type, its background comes with blue but its icon does not appear. Here is the image from the bug. 
I simply use it from your USAGE part.

![whatsapp image 2017-08-01 at 6 12 22 pm](https://user-images.githubusercontent.com/6813862/28832437-153b8a4e-76e5-11e7-8e11-c6beef905dc7.jpeg)

**Comment by candostdagdeviren** [comment]
Hey! Thanks for using :) I'll try to take a look at this week but not promise. If you have time, all PRs are always welcome :)

**Comment by kuraydev** [comment]
Hey, I've tested every type but none of them comes with its own image :( If i can spare time i will examine the bug :)

**Comment by candostdagdeviren** [comment]
We have all the images under `Assets` folder. There should be some problem while loading the images.

**Comment by candostdagdeviren** [comment]
Hello again, finally I had time to test this. I didn't see any problem when I use example project and another project with CocoaPods. I tried all the types and it seems all of them are working. Did you succeed to use it with an image? Does the bug still occur?

**Comment by roc-chang** [comment]
I have the same problem. Did you fixed it?

**Comment by zhangyuepeng86** [comment]
I sovled it as bellow
<img width="261" alt="2017-08-31 17 06 35" src="https://user-images.githubusercontent.com/3301772/29915594-d918abe0-8e6e-11e7-800d-d799b22b3738.png">

**Comment by candostdagdeviren** [comment]
Ah, that's most probably about resources in podspec. I'll take a look soon as a package fix.

**Comment by arsonik** [comment]
is it possible to still have that problem ? @candostdagdeviren 
Because I do, with the latest version

**Comment by candostdagdeviren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CDAlertView Bug](https://trello.com/c/eBGcodOa/205-cdalertview-bug)

**Comment by candostdagdeviren** [comment]
I'll try to take a look at this one soon. When I tested, it was working. Maybe something changed with new CocoaPods version.

**Comment by giuseppe69** [comment]
hi, i have imported your library manually and i have the same problem.

**Comment by candostdagdeviren** [comment]
@giuseppe69 @arsonik new version is released `0.8.2`. I updated all icons with better resolution ones. Updated podspec and handling resources. I tried with both example project and some other project. All icons are working. If you still have a problem with the header icons, please open a new issue with more details :)

**Comment by giuseppe69** [comment]
Thank you, i’ll try as soon as possible. :-)
