### ISSUE TITLE
Many method are not available to used in Objective-C.

### ISSUE THREAD

**Issue by Ferannor** [candostdagdeviren/CDAlertView#25]
Hi,

I try to use CDAlertView in a Obj-C project but I've noticed some methods are not available. For exemple  hide(animations: CDAlertAnimationBlock? = nil, isPopupAnimated: Bool) is not here. 

I've install the library with CocoaPods. 

To try, I've created a new method in CDAlertView : 

`public func hide(isPopupAnimated: Bool) {
        self.hide(animations: nil, isPopupAnimated: isPopupAnimated)
   }`

This one appear in the generated .h. It seem like the CDAlertAnimationBlock is the problem.

**Comment by candostdagdeviren** [comment]
Hello!

Sorry for late response as I was in holidays. Some Swift features (`inout` in this case) are not available in Objective-C. So, bridging `CDAlertAnimationBlock` will not be included in Objective-C.

**Comment by candostdagdeviren** [comment]
Fixed with [CDAlertView version 0.6.1](https://github.com/candostdagdeviren/CDAlertView/releases/tag/0.6.1)
