### ISSUE TITLE
support swift4?

### ISSUE THREAD

**Issue by Mosaics** [candostdagdeviren/CDAlertView#27]

**Comment by candostdagdeviren** [comment]
Hello! I'll add support for Swift 4 probably this weekend.

**Comment by Mosaics** [comment]
tks!

**Comment by ykeisuke** [comment]
@Mosaics @candostdagdeviren Hello! φ('ᴗ'」)
I did support swift4 on my repository after fork your branch.

URL:
https://github.com/ykeisuke/CDAlertView/tree/swift4

Usage:
```Podfile
pod 'CDAlertView', git:'https://github.com/ykeisuke/CDAlertView.git', branch:'swift4'
```
@candostdagdeviren  I'll make pull request. Can you review?

Thanks ʕ•̫͡•ʔ

**Comment by candostdagdeviren** [comment]
Hello! Thanks @ykeisuke for the PR. I'm reviewing at the moment. :)

**Comment by candostdagdeviren** [comment]
<img width="299" alt="screen shot 2017-10-04 at 06 45 53" src="https://user-images.githubusercontent.com/1971963/31160304-bee87234-a8cf-11e7-9811-d0700b751e4c.png">

Huge thanks for @ykeisuke for the contribution! 🚀 I just merged PR and released a new version. @Mosaics you can now use version `0.7.0` to use CDAlertView with Swift 4. 🎉
