### ISSUE TITLE
Tap on headerView / circle icon

### ISSUE THREAD

**Issue by ghbogdan** [candostdagdeviren/CDAlertView#30]
It would be nice to be able to tap on the circle icon and dismiss the alert.

**Comment by candostdagdeviren** [comment]
It can mix up with dragging & dismissing the `CDAlertView`. Therefore, I'm not really a fan of doing this actually.

**Comment by ghbogdan** [comment]
Hmm, it makes sense. Thanks.

**Comment by candostdagdeviren** [comment]
Since there is no one else requested and I'm not a fan of doing this, closing the issue. Thanks for the idea :)
