### ISSUE TITLE
Appearance issue with no action buttons

### ISSUE THREAD

**Issue by rstewart22** [candostdagdeviren/CDAlertView#34]
I'm seeing a strange issue after updating to 0.8.0 recently - when presenting the alerts, the bottom corners are not rounded.

Any ways to rectify this?

<img width="293" alt="screen shot 2018-04-09 at 09 27 25" src="https://user-images.githubusercontent.com/2641468/38500483-8b5631da-3bd8-11e8-8c97-fb1801f3047e.png">

**Comment by candostdagdeviren** [comment]
![screen shot 2018-04-10 at 11 14 58](https://user-images.githubusercontent.com/1971963/38547839-72acba5e-3cb0-11e8-9ff2-af86be9e333d.png)
Fixed with `0.8.1` Thanks @richste for all help on this!
