### ISSUE TITLE
Handle action on tap

### ISSUE THREAD

**Issue by cdeck95** [candostdagdeviren/CDAlertView#39]
It isn't very clear in the documentation on how to handle different actions with a completion handler. Can someone please let me know how I can detect whether my "done action" or "cancel action" buttons are hit? Code is below. Thanks!

`let alert = CDAlertView(title: "Deleting All Accounts", message: "Are you sure you wish to delete all accounts?", type: .warning)
        
let doneAction = CDAlertViewAction(title: "Sure! 💪")
alert.add(action: doneAction)
        let nevermindAction = CDAlertViewAction(title: "Nevermind 😬")
        alert.add(action: nevermindAction)
        alert.show()`

**Comment by candostdagdeviren** [comment]
Hello, 

Thanks for letting me know that action documentation isn't clear.

When you look at the code under [Advanced Action Initialization](https://github.com/candostdagdeviren/CDAlertView#advanced-action-initialization) in Readme, you'll see there is a handler parameter. You can pass a closure to handle your tap on specified to the action button.

I'll try to update the documentation for actions soon.

**Comment by cdeck95** [comment]
Hi,

Thanks for the help! After re-reading, it makes perfect sense and I was able to create the handler. I must have been staring at my screen too long yesterday because idk how I missed that!

For anyone else who finds this issue, please see how I handled the code below:

```
@IBAction func buttonClicked(_ sender: Any) {
        let alert = CDAlertView(title: "Title", message: "Confirming?", type: .warning)
        let doneAction = CDAlertViewAction(title: "Sure! 💪",
                                           font: UIFont.systemFont(ofSize: 17),
                                           textColor: UIColor(red: 27 / 255, green: 169 / 255, blue: 225 / 255, alpha: 1),
                                           backgroundColor: nil,
                                           handler: { action in self.doSomething()})
        alert.add(action: doneAction)
        let nevermindAction = CDAlertViewAction(title: "Nevermind 😬")
        alert.add(action: nevermindAction)
        alert.show()
    }


func doSomething(){
           //do something
    }
```
