### ISSUE TITLE
is can check if there is alert presented or not  from CDAlertView Type 

### ISSUE THREAD

**Issue by salah-mohammed** [candostdagdeviren/CDAlertView#41]
is can check if there is alert presented or not  from CDAlertView Type

**Comment by candostdagdeviren** [comment]
Hello! I didn't understand the problem/question exactly. Could you give a bit more details?

**Comment by candostdagdeviren** [comment]
I'm closing this issue since there is no answer. Feel free to open a new issue if you still have problems/questions.
