### ISSUE TITLE
3 buttons or more in alert

### ISSUE THREAD

**Issue by n2waf** [candostdagdeviren/CDAlertView#45]
when i but 3 buttons in the alert it show me like this 
[link](https://www.photobox.co.uk/my/photo/full?photo_id=501696469030)
i think should the alert be like that 🤔
[link](https://www.photobox.co.uk/my/photo/full?photo_id=501696468170)

**Comment by candostdagdeviren** [comment]
hello! thanks for submitting an issue. The photos you shared are not accessible.

**Comment by n2waf** [comment]
i'm sorry it's bad website
here 
what i see 
[link](https://imgur.com/NvXqWLB)
what should i see
[link](https://imgur.com/7HVneUN)

**Comment by candostdagdeviren** [comment]
did you try to set `isActionButtonsVertical` to `true`?

**Comment by n2waf** [comment]
niccccce thankkk u ❤️👌🏻
