### ISSUE TITLE
Swift 5 

### ISSUE THREAD

**Issue by GenCastro** [candostdagdeviren/CDAlertView#46]
Hello, I don't know if anyone is still maintaining this useful project.
If there is, can you please help convert this project to the latest swift version.

**Comment by candostdagdeviren** [comment]
Hello @GenCastro, thanks for submitting the issue. Do you have a work-in-progress PR to update to Swift 5? If so, I can help in the process.

**Comment by GenCastro** [comment]
No, I don't have a PR. I will try to make one when I have time.

**Comment by GenCastro** [comment]
@candostdagdeviren I have a PR on Swift 5 conversion

**Comment by candostdagdeviren** [comment]
Hello! thanks for the PR, I'll review the PR as soon as possible

**Comment by candostdagdeviren** [comment]
resolved by #47
