### ISSUE TITLE
Add empty type to use without circle at the top

### ISSUE THREAD

**Issue by candostdagdeviren** [candostdagdeviren/CDAlertView#6]
Add an empty type to hide circle at the top. By this, users will be able to use the alert like default `UIAlertController`

**Comment by neeraj92144** [comment]
but it is showing error ( Type 'CDAlertViewType?' has no member 'empty' ) message when I wrote this peace of code as I already imported CDAlertView: -> 
let alert = CDAlertView(title: "Title", message: "message", type: .empty)

**Comment by candostdagdeviren** [comment]
Sorry for the late response. I just saw this. Don't know why didn't see the notification. The type of `empty` is not there yet. This is the issue for this feature request. If you would like to use your own image, you can use `custom` type in `CDAlertViewType`

**Comment by candostdagdeviren** [comment]
Released with version 0.8.0
